## Data processing - save into a txt file

In [2]:
import pandas as pd 
df = pd.read_csv("../data.csv")

In [19]:
df = df.dropna()
df.head()

,article_id,source_id,source_name,author,title,description,url,url_to_image,published_at,content,category,full_content
6,89551,al-jazeera-english,Al Jazeera English,Kaushik Raj,Pro-Israel rallies allowed in India but Palest...,"India, the first non-Arab country to recognise...",https://www.aljazeera.com/news/2023/10/25/pro-...,https://www.aljazeera.com/wp-content/uploads/2...,2023-10-25 09:58:17.000000,"New Delhi, India Israels relentless bombing of...",Nepal,"India, the first non-Arab country to recognise..."
12,89563,the-times-of-india,The Times of India,Durgesh Nandan Jha,PM Hasina’s war on terror gets daughter India’...,India News: NEW DELHI: India preferred Banglad...,https://timesofindia.indiatimes.com/india/pm-h...,"https://static.toiimg.com/thumb/msid-47529300,...",2023-11-02 01:12:47.000000,Ranked! Worlds most loved landmarks; Taj Mahal...,Nepal,NEW DELHI: India preferred Bangladesh over Nep...
21,89584,rt,RT,RT,India leads in migration to 'high-income' coun...,"US, Australia and Canada were the top destinat...",https://www.rt.com/india/585738-indians-migrat...,https://mf.b37mrtl.ru/files/2023.10/article/65...,2023-10-25 06:46:38.000000,India topped a chart of countries with the lar...,Nepal,India has topped a list of countries with the ...
31,89602,rt,RT,RT,India rejects its ranking in Global Hunger Ind...,New Delhi labelled index as “an erroneous meas...,https://www.rt.com/india/584837-india-rejects-...,https://mf.b37mrtl.ru/files/2023.10/article/65...,2023-10-13 14:33:26.000000,The Indian government has rejected the new edi...,Nepal,The Indian government has rejected the new ed...
35,89614,abc-news,ABC News,The Associated Press,A 5.2 magnitude earthquake in Nepal damages do...,A 5.2 magnitude earthquake and some aftershock...,https://abcnews.go.com/International/wireStory...,https://s.abcnews.com/images/US/abc_news_defau...,2023-10-22 15:34:02.000000,"KATHMANDU, Nepal -- A 5.2 magnitude earthquake...",Nepal,"KATHMANDU, Nepal --A 5.2 magnitudeearthquakean..."

In [20]:
df['title'].tolist()[0:2]

['Pro-Israel rallies allowed in India but Palestine solidarity sees crackdown',
 'PM Hasina’s war on terror gets daughter India’s vote in WHO']

In [21]:
## save the titles into a txt file
with open("../data.txt", "a") as f:
    for title in df['title'].tolist():
        f.write(str(title))
        f.write("\n")